/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef package_CONSTANTS_H
#define package_CONSTANTS_H

#include "package_types.h"



class packageConstants {
 public:
  packageConstants();

};

extern const packageConstants g_package_constants;



#endif
